version: "2"
services: 
  db:
    networks:
      - db-network

  migrations:
    environment:
      - NODE_ENV=production
      - PORT=5000
      - AWS_DEFAULT_REGION=us-east-1
      - DB_URL=postgres://postgres:postgres@db/postgres
      - DB_URL_TEST=postgres://username:Dummy123@postgres/georio-store
    command: yarn db:migrate
    networks: 
      - db-network
  
  georio: 
    environment:
      - NODE_ENV=production
      - PORT=5000
      - AWS_DEFAULT_REGION=us-east-1
      - DB_URL=postgres://postgres:postgres@db/postgres
      - DB_URL_TEST=postgres://username:Dummy123@postgres/georio-store 
    command: yarn docker:start
    networks:
      - app-network
      - db-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - georio
    networks:
      - app-network
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email info@axismaps.com --agree-tos --no-eff-email --staging -d beirut.georio.levantcarta.org  -d beirut.georio.levantcarta.org

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/sammy/node_project/views/
      o: bind

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
