version: "3"
services: 
  db:
    image: geographica/postgis:dev_diplodocus
    volumes:
      - ./db-data:/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - "9001:5432"
  
  migrations:
    build: .
    volumes: 
      - .:/app
    links: 
      - db
    depends_on: 
      - db

  georio:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000" 
    depends_on: 
      - migrations
    links: 
      - db
  
  tilecache:
    build: .
    volumes:
      - .:/app
    depends_on: 
      - migrations
    links: 
      - db
    command: node bin/tile-cache.js