version: "3"
services: 
  db:
    networks:
      - db-network

  migrations:
    environment:
      - NODE_ENV=production
      - PORT=5000
      - AWS_DEFAULT_REGION=us-east-1
      - POSTGRES_PASSWORD=postgres
      - DB_URL=postgres://postgres:postgres@db/postgres
      - DB_URL_TEST=postgres://username:Dummy123@postgres/georio-store
    networks: 
      - db-network
  
  georio: 
    environment:
      - NODE_ENV=production
      - PORT=5000
      - AWS_DEFAULT_REGION=us-east-1
      - HOST=beirut.georio.levantcarta.org
      - DB_URL=postgres://postgres:postgres@db/postgres
      - DB_URL_TEST=postgres://username:Dummy123@postgres/georio-store 
    command: ["./bin/wait-for-end.sh", "migrations", "yarn", "docker:start"]
    networks:
      - app-network
      - db-network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - georio
    networks:
      - app-network
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - .:/app
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/app/public --email info@axismaps.com --agree-tos --no-eff-email -d beirut.georio.levantcarta.org

volumes:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
