previewsEnabled: true
services:
  - type: web
    name: levant-carta
    region: oregon
    env: node
    healthCheckPath: /health
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - fromGroup: levant-carta
      - key: DB_URL
        fromDatabase:
          name: levantcarta
          property: connectionString
      - key: DB_URL_TEST
        fromDatabase:
          name: levantcarta
          property: connectionString
      - key: DB_SSL
        value: false
databases:
  - name: levantcarta
